version: '3'
services:
  jenkins:
        image: jenkins/jenkins:lts-jdk11
        restart: always
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - ./workspace:/var/jenkins_home
        environment:
            - JAVA_OPTS=-Xmx1024m
            # - JAVA_OPTS=-Xmx2048m